# Generated by Django 4.2.6 on 2023-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Descriptions', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Posttitle',
        ),
    ]
